### PR TITLE
Add syntax highlightning to README

### PR DESCRIPTION
**Pull request by HeavyRain266**
Now code examples in README are more readable.

### CODE REVIEW

**Comment by bmarty** [comment]
Hi @HeavyRain266 , thanks for the PR.
Can you add a sign off so that I will be able to merge it? You can find more information about how to do that here: https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off

Thanks!

**Comment by HeavyRain266** [comment]
I'm sorry but I cannot do that through mercurial extension for git, feel free to make those changes on your own.

**Comment by bmarty** [comment]
That's sad. I little comment to this PR with
> Signed-off-by: Your Name <your@email.example.org>

is enough! Please do it 🙏 !

**Comment by HeavyRain266** [comment]
Signed-off-by: HeavyRain266 ignacy432@gmail.com

**Pull request merged**
